### ISSUE TITLE
openpilotkr model 이슈

### ISSUE THREAD

**Issue by TurboCE** [TurboCE/dragonpilot#4]
Traceback (most recent call last):
  File "./plannerd.py", line 58, in <module>
    main()
  File "./plannerd.py", line 54, in main
    plannerd_thread(sm, pm)
  File "./plannerd.py", line 34, in plannerd_thread
    lateral_planner = LateralPlanner(CP)
  File "/data/pythonpath/selfdrive/controls/lib/lateral_planner.py", line 39, in __init__
    self.lat_mpc = LateralMpc()
  File "/data/pythonpath/selfdrive/controls/lib/lateral_mpc_lib/lat_mpc.py", line 122, in __init__
    self.reset(x0)
  File "/data/pythonpath/selfdrive/controls/lib/lateral_mpc_lib/lat_mpc.py", line 129, in reset
    self.solver.cost_set(i, "yref", self.yref[i])
  File "pyextra/acados_template/acados_ocp_solver_pyx.pyx", line 577, in acados_template.acados_ocp_solver_pyx.AcadosOcpSolverCython.cost_set
Exception: AcadosOcpSolverCython.cost_set(): mismatching dimension for field "yref" at stage 0 with dimension (5, 0) (you have (3, 0))

**Comment by TurboCE** [comment]
loaded model with size: 1221118
ioctl returned -1 with errno 22
{"event": "fingerprinted", "car_fingerprint": "CHEVROLET BOLT EUV 2022", "source": 2, "fuzzy": false, "cached": false, "fw_count": 0, "ecu_responses": [], "vin_rx_addr": 0, "error": true}
Starting listener for: camerad
selfdrive/modeld/modeld.cc: connected main cam with buffer size: 1526004 (1164 x 874)
Thneed::clexec: running 0 queued kernels
CAUTION: model output is NULL, does it have no outputs?
Thneed::stop: recorded 0 commands
ioctl returned -1 with errno 22
selfdrive/modeld/thneed/thneed.cc:318: void Thneed::execute(float **, float *, bool): assertion "ret == 0" failed
model: input_img -> outputs
input product is 307200
selfdrive/modeld/runners/snpemodel.cc:117: SNPEModel::SNPEModel(const char *, float *, size_t, int, bool): assertion "output_size == bufferShape[1]" failed
Logged current crash to /data/media/0/crash_logs/2023-01-03-18-08-45.log
crash
Traceback (most recent call last):
  File "/data/openpilot/selfdrive/manager/process.py", line 43, in launcher
    getattr(mod, 'main')()
  File "/data/openpilot/selfdrive/controls/plannerd.py", line 54, in main
    plannerd_thread(sm, pm)
  File "/data/openpilot/selfdrive/controls/plannerd.py", line 34, in plannerd_thread
    lateral_planner = LateralPlanner(CP)
  File "/data/openpilot/selfdrive/controls/lib/lateral_planner.py", line 39, in __init__
    self.lat_mpc = LateralMpc()
  File "/data/openpilot/selfdrive/controls/lib/lateral_mpc_lib/lat_mpc.py", line 122, in __init__
    self.reset(x0)
  File "/data/openpilot/selfdrive/controls/lib/lateral_mpc_lib/lat_mpc.py", line 129, in reset
    self.solver.cost_set(i, "yref", self.yref[i])
  File "pyextra/acados_template/acados_ocp_solver_pyx.pyx", line 577, in acados_template.acados_ocp_solver_pyx.AcadosOcpSolverCython.cost_set
Exception: AcadosOcpSolverCython.cost_set(): mismatching dimension for field "yref" at stage 0 with dimension (5, 0) (you have (3, 0))
Process plannerd:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/openpilot/selfdrive/manager/process.py", line 43, in launcher
    getattr(mod, 'main')()
  File "/data/openpilot/selfdrive/controls/plannerd.py", line 54, in main
    plannerd_thread(sm, pm)
  File "/data/openpilot/selfdrive/controls/plannerd.py", line 34, in plannerd_thread
    lateral_planner = LateralPlanner(CP)
  File "/data/openpilot/selfdrive/controls/lib/lateral_planner.py", line 39, in __init__
    self.lat_mpc = LateralMpc()
  File "/data/openpilot/selfdrive/controls/lib/lateral_mpc_lib/lat_mpc.py", line 122, in __init__
    self.reset(x0)
  File "/data/openpilot/selfdrive/controls/lib/lateral_mpc_lib/lat_mpc.py", line 129, in reset
    self.solver.cost_set(i, "yref", self.yref[i])
  File "pyextra/acados_template/acados_ocp_solver_pyx.pyx", line 577, in acados_template.acados_ocp_solver_pyx.AcadosOcpSolverCython.cost_set
Exception: AcadosOcpSolverCython.cost_set(): mismatching dimension for field "yref" at stage 0 with dimension (5, 0) (you have (3, 0))
